[package]
name = "encrust-core"
description = "Core functionality for the encrust crate"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rand = { "version" = "0.10.1", default-features = false, features = ["alloc"] }
zeroize = { version = "1.6.0", features = ["derive"] }
rapidhash = { version = "4.1.0", default-features = false, optional = true }

[dev-dependencies]
rand = { "version" = "0.10.1", default-features = false, features = ["thread_rng"] }

[features]
all = ["macros", "hashstrings"]
default = ["macros", "hashstrings"]
macros = []
hashstrings = ["dep:rapidhash"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true