name: Rust - CI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Linting and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - name: Clippy
        run: cargo clippy --workspace --all-features -- -D warnings
      - name: Format
        run: cargo fmt --all -- --check --verbose

  build:
    name: Test and build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: stable
      - name: Build
        run: cargo build --all-targets --all-features --workspace --verbose
      - name: Run tests
        run: cargo test --all-features --workspace --verbose

  miri:
    name: Miri
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          components: miri
      - name: Miri
        run: cargo miri test --workspace --verbose

  miri_s390x:
    name: Miri s390x (big endian)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          components: miri
          targets: s390x-unknown-linux-gnu
      - name: Miri
        run: cargo miri test --target=s390x-unknown-linux-gnu --workspace --verbose

  no_std:
    name: Build and run no_std
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: stable
      - name: Build
        run: cargo build --manifest-path test_crates/nostd_compile/Cargo.toml
      - name: Run
        run: cargo run --manifest-path test_crates/nostd_compile/Cargo.toml

  msrv:
    name: Verify MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: 1.85.0
      - name: Build
        run: cargo build --all-targets --all-features --workspace --verbose
      - name: Run tests
        run: cargo test --all-features --workspace --verbose